AllCops:
  Exclude:
    - bin/**
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - aiwolf.gemspec
    - spec/**/*_spec.rb
Metrics/LineLength:
  Exclude:
    - aiwolf.gemspec

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '()'
    '%w': '()'
    '%W': '()'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
